# -*- coding: utf-8 -*-

[package]
name = "cms-backd"
version = "1.0.0"
edition = "2021"
license = "GPL-2.0-or-later"
authors = [ "Michael Büsch <m@bues.ch>" ]
publish = false

[dependencies]
anyhow = "1"
async-recursion = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
cms-ident = { path = "../cms-ident" }
cms-seccomp = { path = "../cms-seccomp" }
cms-socket = { path = "../cms-socket" }
cms-socket-back = { path = "../cms-socket-back" }
cms-socket-db = { path = "../cms-socket-db" }
cms-socket-post = { path = "../cms-socket-post" }
configparser = "3"
crunchy = { git = "https://github.com/mbuesch/crunchy.git", rev = "433a4d08b859031f22d80197931c555c8af7b1fb" }
html-escape = "0.2"
lru = "0.12"
multipeek = "0.1"
tokio = { version = "1", features = [ "rt", "rt-multi-thread", "sync", "signal", "macros" ] }

# vim: ts=4 sw=4 expandtab
