# -*- coding: utf-8 -*-

[package]
name = "cms-seccomp"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"
authors = [ "Michael Büsch <m@bues.ch>" ]
publish = false

[dependencies]
anyhow = "1"
libc = "0.2"
seccompiler = "0.4"

# vim: ts=4 sw=4 expandtab
